// Ambient augmentation for this Worker's bindings (declared in wrangler.toml).
// Normally generated by `wrangler types`; declared by hand here since that
// hasn't been run for this project. Merges into the `Cloudflare.Env`
// interface that @cloudflare/workers-types declares as extensible.
declare namespace Cloudflare {
	interface Env {
		RATE_LIMITER?: RateLimit;
	}
}
